project_id = "uxmezklevgkqelahibqy"

[functions.execute-import]
verify_jwt = true

[functions.access-attachment]
verify_jwt = false

[functions.scim]
verify_jwt = false

[functions.generate-update-summary]
verify_jwt = true
