project_id = "uxmezklevgkqelahibqy"

[functions.execute-import]
verify_jwt = true

[functions.access-attachment]
verify_jwt = false

[functions.scim]
verify_jwt = false

[functions.sso-initiate]
verify_jwt = false

[functions.sso-callback]
verify_jwt = false

[functions.sso-metadata]
verify_jwt = false

[functions.generate-update-summary]
verify_jwt = true

[functions.analyze-attachment]
verify_jwt = true

[functions.generate-case-number]
verify_jwt = false
